### ISSUE TITLE
usage with preact-mdl

### ISSUE THREAD

**Issue by 11111000000** [developit/preact-cycle#3]
with `import {h,render} from 'preact-cycle'` we got `[object][object][object]` instead of html

**Comment by developit** [comment]
@11111000000 Here's a demo of `preact-cycle` + `preact-mdl`:
https://jsfiddle.net/developit/jdrLyxad/

Anything in there different from what you did?

Generally if you're getting `[object][object][object]` it means you have two copies of Preact in your dependency tree.

**Comment by 11111000000** [comment]
yes, when I remove 'preact' from 'package.json' and leave only 'preact-cycle', it works, thanks!

**Comment by developit** [comment]
Awesome!
